version: "3.7"

services:
  frontend:
    build:
      context: ./../frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:8080/graphql"
        NEXT_PUBLIC_OAUTH_REDIRECT_URL: "http://localhost:3005"
        NEXT_PUBLIC_OAUTH_CLIENT_ID: "frontend"
        NEXT_PUBLIC_OAUTH_AUTHORITY: "http://localhost:9009/realms/GITS"
    ports:
      - "3005:3000"
    networks:
      - dapr-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "9009:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    volumes:
      # Mounts in our folder need to first exit the folder and enter it again "./../frontend"
      # This is necessary because of how docker-compose resolves paths when merging multiple compose files
      - type: bind
        source: ./../frontend/keycloak-realm
        target: /opt/keycloak/data/import
      - ./../frontend/keycloak-theme:/opt/keycloak/themes
    networks:
      - dapr-network

networks:
  dapr-network:
    name: dapr-network
    external: true
