// src/data/achievementsData.ts
export const achievementsData = [
  {
    id: 1,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-06T10:00:00"),
    courseId: "course1",
  },
  {
    id: 2,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-07T10:00:00"),
    courseId: "course1",
  },
  {
    id: 3,
    title: "Created a Course",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course1",
  },
  {
    id: 4,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-09T10:00:00"),
    courseId: "course1",
  },
  {
    id: 5,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-10T10:00:00"),
    courseId: "course1",
  },
  {
    id: 6,
    title: "Created a Course",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course1",
  },
  {
    id: 7,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-12T10:00:00"),
    courseId: "course1",
  },
  {
    id: 8,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-13T10:00:00"),
    courseId: "course1",
  },
  {
    id: 9,
    title: "Created a Course",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course2",
  },
  {
    id: 10,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-15T10:00:00"),
    courseId: "course2",
  },
  {
    id: 11,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-16T10:00:00"),
    courseId: "course1",
  },
  {
    id: 12,
    title: "Created a Course",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course2",
  },
  {
    id: 13,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-18T10:00:00"),
    courseId: "course2",
  },
  {
    id: 14,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-19T10:00:00"),
    courseId: "course1",
  },
  {
    id: 15,
    title: "Created a Course",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course1",
  },
  {
    id: 16,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-21T10:00:00"),
    courseId: "course2",
  },
  {
    id: 17,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-22T10:00:00"),
    courseId: "course2",
  },
  {
    id: 18,
    title: "Created a Course",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course1",
  },
  {
    id: 19,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-24T10:00:00"),
    courseId: "course1",
  },
  {
    id: 20,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-25T10:00:00"),
    courseId: "course2",
  },
  {
    id: 21,
    title: "Created a Course and this is very long just to check it out",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course2",
  },
  {
    id: 19,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-24T10:00:00"),
    courseId: "course3",
  },
  {
    id: 20,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-25T10:00:00"),
    courseId: "course4",
  },
  {
    id: 21,
    title: "Created a Course and this is very long just to check it out",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course5",
  },
  {
    id: 19,
    title: "First Login",
    description: "You logged in for the first time!",
    icon: "🏅",
    achieved: true,
    achievedAt: new Date("2025-06-24T10:00:00"),
    courseId: "course6",
  },
  {
    id: 20,
    title: "Completed Survey",
    description: "You completed your first survey.",
    icon: "✅",
    achieved: true,
    achievedAt: new Date("2025-06-25T10:00:00"),
    courseId: "course7",
  },
  {
    id: 21,
    title: "Created a Course and this is very long just to check it out",
    description: "You created your first course.",
    icon: "📘",
    achieved: false,
    achievedAt: null,
    courseId: "course8",
  },
];
